name : deploy

on:
  push:
    branches:
      - main

jobs: 
  cdk-deployment: 
    name: deploy cdk 
    runs-on: ubuntu-latest

    permissions : 
      id-token: write 
      contents: read 

    steps: 
      - uses: actions/checkout@v4 
        name: checkout repository version v2 owner actions 

        
      - name: Install node.js 
        uses: actions/setup-node@v4
        with: 
          node-version: 22
               
      - name: install dependencies listed in package.json
        run: npm install

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: GitHub-Action-Role
          aws-region: us-east-1


      - name: cdk synth 
        run: npx cdk synth  
        env:
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          CLOUDFRONT_CERT_ARN: ${{ secrets.CLOUDFRONT_CERT_ARN }}
          ALB_CERT_ARN: ${{ secrets.ALB_CERT_ARN }}

    
      - name: cdk deploy
        run: npx cdk deploy --require-approval never 

     








